//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate_Management.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGeneralAccountLandSale
    {
        public Nullable<System.Guid> guid { get; set; }
        public Nullable<int> c { get; set; }
        public string title { get; set; }
        public string paytype { get; set; }
        public Nullable<decimal> totalnet { get; set; }
        public Nullable<decimal> payments { get; set; }
        public Nullable<decimal> remain { get; set; }
    }
}
