//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate_Management.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLandQty
    {
        public Nullable<System.Guid> Guid { get; set; }
        public Nullable<int> code { get; set; }
        public string blocknumber { get; set; }
        public string land { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> workfee { get; set; }
        public Nullable<decimal> workfeevalue { get; set; }
        public int qty { get; set; }
        public string status { get; set; }
    }
}
