//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate_Management.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLandTran
    {
        public System.Guid guid { get; set; }
        public Nullable<System.Guid> landguid { get; set; }
        public int number { get; set; }
        public string land { get; set; }
        public string agent { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public string deednumber { get; set; }
        public string buildingnumber { get; set; }
        public Nullable<decimal> buildingfeevalue { get; set; }
        public Nullable<decimal> remain { get; set; }
        public string note { get; set; }
    }
}
