//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate_Management.Data.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class realestatebrokermanagementEntities : DbContext
    {
        public realestatebrokermanagementEntities()
            : base("name=realestatebrokermanagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbLog> tbLogs { get; set; }
        public virtual DbSet<tbPlan> tbPlans { get; set; }
        public virtual DbSet<tbLawyer> tbLawyers { get; set; }
    }
}
