//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate_Management.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLog
    {
        public System.Guid PlanGuid { get; set; }
        public System.Guid Guid { get; set; }
        public int Code { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string UserName { get; set; }
        public string ActionType { get; set; }
        public string Action { get; set; }
        public string Note { get; set; }
    }
}
