//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate_Management.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOwner
    {
        public System.Guid PlanGuid { get; set; }
        public System.Guid Guid { get; set; }
        public int Code { get; set; }
        public string Statues { get; set; }
        public Nullable<int> Number { get; set; }
        public string Name { get; set; }
        public string IDNumber { get; set; }
        public string Mobile { get; set; }
        public string MobileAdd { get; set; }
        public string Email { get; set; }
        public string VatNumber { get; set; }
        public string PublicNumber { get; set; }
        public string AgentName { get; set; }
        public string AgentID { get; set; }
        public string AgentMobile { get; set; }
        public string AgenteMail { get; set; }
        public string AgentVatNumber { get; set; }
        public string AgencyNumber { get; set; }
        public string AgentPublicNumber { get; set; }
        public string OfficeName { get; set; }
        public string OfficeCR { get; set; }
        public string OfficePhone { get; set; }
        public string OfficeeMail { get; set; }
        public string OfficeVatNumber { get; set; }
        public string OfficePublicNumber { get; set; }
        public string Note { get; set; }
        public string LastAction { get; set; }
    }
}
