//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate_Management.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPlan
    {
        public System.Guid OwnerGuid { get; set; }
        public System.Guid Guid { get; set; }
        public int Code { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Location { get; set; }
        public string Note { get; set; }
        public string LastAction { get; set; }
    }
}
