//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate_Management.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAccountBalance
    {
        public Nullable<System.Guid> guid { get; set; }
        public Nullable<int> number { get; set; }
        public string name { get; set; }
        public int amountin { get; set; }
        public Nullable<decimal> amountout { get; set; }
        public int balance { get; set; }
    }
}
