//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Real_Estate_Management.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDailSell
    {
        public Nullable<System.Guid> guid { get; set; }
        public System.Guid payguid { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<int> code { get; set; }
        public string land { get; set; }
        public Nullable<int> contractno { get; set; }
        public Nullable<decimal> cash { get; set; }
        public decimal network { get; set; }
        public decimal chick { get; set; }
        public decimal bank { get; set; }
        public string bankname { get; set; }
        public string checkno { get; set; }
        public int paynumber { get; set; }
        public int payrefnumber { get; set; }
        public string paydate { get; set; }
        public string status { get; set; }
    }
}
